app/urls.py
from django.urls import path
from . import views
app_name='app'
urlpatterns = [
    path("", views.BaseView.as_view(), name="base"),
   
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class BaseView(TemplateView):
    template_name='base.html'





# Create your views here.

app/templates/base.html
{% load static  %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    
    <title>YouTube</title>
    <link rel="shortcut icon" href="{% static 'icon.ico' %}">
  </head>
  
<!--ヘッダー-->
  <body>
    <header class="header">

       
    
        <!-- ハンバーガーメニュー部分 -->
        <div class="nav">
    
          <!-- ハンバーガーメニューの表示・非表示を切り替えるチェックボックス -->
          <input id="drawer_input" class="drawer_hidden" type="checkbox">
    
          <!-- ハンバーガーアイコン -->
          <label for="drawer_input" class="drawer_open"><span></span></label>
    
          <!-- メニュー -->
          <nav class="nav_content">
            <ul class="nav_list">
              
              <li class="nav_item"><a href="{% url 'app:base' %}">HOME</a></li>
              <li class="nav_item"><a href="short.html">ショート</a></li>
              <li class="nav_item"><a href="touroku.html">登録チャンネル</a></li>
              <li class="nav_item"><a href="library.html">ライブラリ</a></li>

            </ul>
          </nav>
   
        </div>
        
      </div>
    </header>
  </body>
  <a href="{% url 'app:base' %}"><img src="{% static 'dekasuginndara.png' %}" alt="YouTude"></a></div>
  <div><form method="get"><input type="search" name="query" type="text" placeholder=" 検索"><button>🔍</button></form></div>
  <a href=''><img src="{% static 'アカウント.png' %}" alt="アカウント"></a></div>


  <nav id ="global navi">
    <ul>
        <li><a href="{% url 'app:base' %}">HOME</a></li>
        <li><a href="short.html">ショート</a></li>
        <li><a href="touroku.html">登録チャンネル</a></li>
        <li><a href="library.html">ライブラリ</a></li>
    </ul>
  </nav>
</header>
<!--ヘッダー-->
<body><a href='https://www.youtube.com/watch?v=qEXN3etfqQs'><img src="{% static 'douga1.png' %}" alt="douga"></a></div></body>
<body><a href='https://www.youtube.com/watch?v=RluzFasfrUo&t=29s'><img src="{% static 'douga1.png' %}" alt="douga"></a></div></body>

  <from id="entry">
   
   
  </from>
</html>